# Generated by Django 5.2.6 on 2025-09-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('FRONTEND', 'Frontend & Design'), ('BACKEND', 'Backend & Languages'), ('DATA_TOOLS', 'Data Science & Tools')], default='FRONTEND', max_length=20),
        ),
    ]
