# Generated by Django 5.2.6 on 2025-09-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('credential_url', models.URLField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificate_pdfs/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
