# Generated by Django 5.2.6 on 2025-09-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_issuer_alter_certificate_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
