# Generated by Django 5.2.6 on 2025-09-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_create_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(default='https://placehold.co/800?text=Project+Image&font=roboto'),
        ),
    ]
