# Generated by Django 5.2.6 on 2025-09-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
