# Generated by Django 5.2.6 on 2025-09-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_certificate_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume_file',
            field=models.URLField(blank=True),
        ),
    ]
