# Generated by Django 5.2.6 on 2025-09-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_profile_resume_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='issuer',
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuers',
            field=models.ManyToManyField(related_name='certificates', to='api.issuer'),
        ),
    ]
