# Generated by Django 5.2.6 on 2025-09-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_certificate_issuer_certificate_issuers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('FRONTEND', 'Frontend & Design'), ('BACKEND', 'Backend & Languages'), ('DATA_TOOLS', 'Data Science & Tools'), ('ENGINEERING TOOLS', 'Engineering Tools')], default='FRONTEND', max_length=20),
        ),
    ]
